// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDLjn-W3Jtxkes_U_gApPTXxtC30jBlXE',
    appId: '1:1061714170696:web:b00a126a648f62352ed97d',
    messagingSenderId: '1061714170696',
    projectId: 'ecommerce-app-96fda',
    authDomain: 'ecommerce-app-96fda.firebaseapp.com',
    storageBucket: 'ecommerce-app-96fda.firebasestorage.app',
    measurementId: 'G-8B2C3NTK35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa5610rfiK0r7Nk6OKJM8ikuH2lVqAUBQ',
    appId: '1:1061714170696:android:0c22e1f51f6175182ed97d',
    messagingSenderId: '1061714170696',
    projectId: 'ecommerce-app-96fda',
    storageBucket: 'ecommerce-app-96fda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDy0x4-I16kiKM8BBWktqesUizfq16fwU',
    appId: '1:1061714170696:ios:650b965c529c3fee2ed97d',
    messagingSenderId: '1061714170696',
    projectId: 'ecommerce-app-96fda',
    storageBucket: 'ecommerce-app-96fda.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDy0x4-I16kiKM8BBWktqesUizfq16fwU',
    appId: '1:1061714170696:ios:650b965c529c3fee2ed97d',
    messagingSenderId: '1061714170696',
    projectId: 'ecommerce-app-96fda',
    storageBucket: 'ecommerce-app-96fda.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDLjn-W3Jtxkes_U_gApPTXxtC30jBlXE',
    appId: '1:1061714170696:web:1a213caf1f66c9722ed97d',
    messagingSenderId: '1061714170696',
    projectId: 'ecommerce-app-96fda',
    authDomain: 'ecommerce-app-96fda.firebaseapp.com',
    storageBucket: 'ecommerce-app-96fda.firebasestorage.app',
    measurementId: 'G-1B5Q8PV8D0',
  );
}
